# Generated by Django 4.1.4 on 2022-12-30 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='category',
            name='sub_category',
            field=models.CharField(max_length=30),
        ),
    ]
