# Generated by Django 4.1.4 on 2022-12-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Female', 'F'), ('Male', 'M')], default='1', max_length=10),
        ),
    ]
