# Generated by Django 4.1.4 on 2022-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0002_alter_employee_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='1', max_length=10),
        ),
    ]
