# Generated by Django 4.1.2 on 2022-11-01 10:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e2cb9d8f-f267-48aa-ba85-1469f0bdf653'), editable=False, primary_key=True, serialize=False),
        ),
    ]
