# Generated by Django 4.1.2 on 2022-11-01 11:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('9d632b40-d92d-4329-bbe7-0cf3c22810d7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
