# Generated by Django 4.1.2 on 2022-11-01 11:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_todo_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('4dda3a85-3805-4964-9c9b-3062ebff53ad'), editable=False, primary_key=True, serialize=False),
        ),
    ]
